openapi: 3.0.4
info:
  title: NextCall API Documentation
  version: "1.0.0"
  description: Comprehensive API documentation for the NextCall platform.

servers:
  - url: http://localhost:3000/api
    description: Development Server

paths:
  # Defining Register API for Document
  /register:
    post:
      summary: Register a new user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: tester@info.com
                password:
                  type: string
                  example: tester@!23
                name:
                  type: string
                  example: Tester
              required:
                - email
                - password
                - name
      responses:
        201:
          description: User registered successfully
        400:
          description: Email already exists

  # Defining login api for Document
  /login:
    post:
      summary: Login with user credentials
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: tester@info.com
                password:
                  type: string
                  example: tester@!23
              required:
                - email
                - password
      responses:
        200:
          description: Login successful
        400:
          description: Invalid password
        404:
          description: User not found
