version: '3.8'

services:
  mongo:
   image: mongo:6.0
   container_name: nextcall-mongo
   restart: unless-stopped
   ports:
    - 27017:27017
   volumes:
    - mongo-data:/data/db
  
  app:
   build: .
   container_name: nextcall-api
   ports:
    - 3000:3000
   depends_on:
    - mongo
   environment:
    - MONGO_URI=mongodb://mongo:27017/nextcalldb
   volumes:
    - .:/usr/src/app
   command: ["node", "src/server.js"]

volumes:
  mongo-data:
